version: "2"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "8080:8080"
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
    restart: always
    depends_on:
      - webapi

